[Defines]
    projectname = "Whitley"
    workspace = "D:\\DCG\\DCG2\\DCG10nm"
    cache_dir = ""


[[Repo]]
    name = 'edk2'
    path = 'Edk2'
    git = 'https://github.com/tianocore/edk2.git'
    branch = 'Downstream/master'
    version = 'head'
[[Repo]]
    name = 'edk2-platforms'
    path = 'Edk2Platforms'
    git = 'https://github.com/tianocore/edk2-platforms.git'
    branch = 'Downstream/master'
    version = 'head'
[[Repo]]
    name = 'FDBin'
    path = 'FDBin'
    git = 'ssh://git-amr-7.devtools.intel.com:29418/iafw-fdbinary.git'
    branch = 'master'
    version = 'head'

[[Repo]]
    name = 'intel'
    path = 'Intel'
    git = 'ssh://git-amr-7.devtools.intel.com:29418/iafw-intel.git'
    branch = 'master'
    version = 'head'

[Basic]
    [[Basic.step]]
        name = "SetupEnv"
        depends = []
        [Basic.step.command]
            cmd = "set"
            parameters = ["PYTHON_HOME=C:\\Python27"]
            path = ['intel','']
        output_type = ['EnvVar','File']
    [[Basic.step]]
        name = "BuildClean"
        depends = []
        [Basic.step.command]
            cmd = '%PYTHON_HOME%\\python.exe'
            parameters = ['WhitleyRpPkg\\PlatformBIOSBuild.py','-cl']
            path = ['intel','']
        output_type = ['File']
    [[Basic.step]]
        name = "BuildPlatform"
        depends = []
        [Basic.step.command]
            cmd = '%PYTHON_HOME%\\python.exe'
            parameters = ['WhitleyRpPkg\\PlatformBIOSBuild.py','-b','RELEASE','-r', 'TEST']
            path = ['intel','']
        output_type = ['File']

[Test]
    [Test.IncrementBuild]
        FileNeedCompare = [['intel','\*LBG_ME11.bin'],['intel','\*HLBG_SPS.bin'],['intel','\*LBG_SPS.bin'],['intel','\*LBG_ME11.rom'],['intel','\*HLBG_SPS.rom'],['intel','\*LBG_SPS.rom']]
        TargetRepo='intel'
    [Test.TestBuild]
        TestMethod = 'Env'
